Django2ByExamples/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

from django.conf import settings
from django.conf.urls.static import static

sitemaps = {'post': PostSitemap}

urlpatterns = [
    path('', include('pages.urls')),
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('account/', include('account.urls', namespace='account')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('images/', include('images.urls', namespace='images')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Функция static() подходит только для локальной разработки, но не для применения на
# боевых серверах. Никогда не используйте Django в качестве поставщика статических
# и медиафайлов.

MyShop/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('', include('shop.urls', namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/urls.py
from django.urls import path, reverse_lazy, re_path
from django.contrib.auth import views as auth_view
from . import views
from .views import MyLogin

app_name = 'account'

urlpatterns = [
    path('users/follow/', views.user_follow, name='user_follow'),
    path('users/', views.user_list, name='user_list'),
    path('user/<username>/', views.user_detail, name='user_detail'),

    # path('login/', views.user_login, name='login'),
    # path('login/', auth_view.LoginView.as_view(), name='login'),
    path('login/', MyLogin.as_view(), name='login'),
    path('logout/', auth_view.LogoutView.as_view(), name='logout'),



    path('password_change/',
         auth_view.PasswordChangeView.as_view(
             success_url=reverse_lazy('account:password_change_done')), name='password_change'),

    path('password_change/done/',
         auth_view.PasswordChangeDoneView.as_view(), name='password_change_done'),


    # -- RESET PASSWORD URLS
    path('password_reset/',
         auth_view.PasswordResetView.as_view(
            success_url=reverse_lazy('account:password_reset_done')), name='password_reset'),

    path('password_reset/done/',
         auth_view.PasswordResetDoneView.as_view(), name='password_reset_done'),

    path('reset/<uidb64>/<token>/',
         auth_view.PasswordResetConfirmView.as_view(
            success_url=reverse_lazy('account:password_reset_complete')), name='password_reset_confirm'),

    path('reset/done/',
         auth_view.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    # -- END OF RESET PASSWORD URLS


    path('register/', views.register, name='register'),
    path('edit/', views.edit, name='edit'),
    path('profile/', views.profile, name='profile'),

    path('', views.dashboard, name='dashboard'),
]

blog/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostsFeed

app_name = 'blog'

urlpatterns = [
    # post views
    path('', views.post_list, name='post_list'),
    # path('', views.PostListView.as_view(), name='post_list'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
    path('search/', views.post_search, name='post_search'),
]

images/urls.py
from django.urls import path
from . import views

app_name = 'images'

urlpatterns = [
    path('create/', views.image_create, name='create'),
    path('like/', views.image_like, name='like'),
    path('images-list/', views.image_list, name='images-list'),
    path('detail/<int:id>/<slug:slug>', views.image_detail, name='detail'),
    path('ranking/', views.image_ranking, name='ranking'),
]

templates/pages/bootstrap.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"
            integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"
            integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k"
            crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
          integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
</head>
<body>
    <div class="container">
    <span class="text-center">
        <h1 class="">Hello, world!</h1>
        <h3>Text color</h3>
        <p class="text-primary ">Bootstrap primary</p>
        <p class="text-success ">Bootstrap success</p>
        <p class="text-info ">Bootstrap info</p>
        <p class="text-danger ">Bootstrap danger</p>
        <p class="text-warning ">Bootstrap warning</p>
        <p class="text-secondary ">Bootstrap secondary</p>
        <p class="text-secondary  bg-info">Bootstrap secondary</p>


        <h3>BG Color text</h3>
        <p class="bg-danger">Bootstrap background color</p>
        <p class="bg-info">Bootstrap background color</p>
        <p class="bg-primary">Bootstrap background color</p>
        <p class="bg-success">Bootstrap background color</p>
        <p class="bg-warning">Bootstrap background color</p>
        <p class="bg-secondary">Bootstrap background color</p>
        <p class="bg-light">Bootstrap background color</p>
        <p class="bg-dark text-white-50">Bootstrap background color</p>
    </span>

    <br>
    <br>
    <br>
    <br>

    <span>
        <div class="display-2 bg-info text-center">Typography</div>
        <h1>Hello, Im 40px</h1>
        <h2>Hello, Im 32px</h2>
        <h3>Hello, Im 28px</h3>
        <h4>Hello, Im 24px</h4>
        <h5>Hello, Im 20px</h5>
        <h6>Hello, Im 16px</h6>
        <br>
        <br>
        <br>
        <div class="h1">Hello, Im 40px DIV</div>
        <div class="h2">Hello, Im 32px DIV</div>
        <div class="h3">Hello, Im 28px DIV</div>
        <div class="h4">Hello, Im 24px DIV</div>
        <div class="h5">Hello, Im 20px DIV</div>
        <div class="h6">Hello, Im 16px DIV</div>
        <br>
        <br>
        <br>
        <div class="display-1">display-1</div>
        <div class="display-2">display-2</div>
        <div class="display-3">display-3</div>
        <div class="display-4">display-4</div>
        <br>
        <br>
        <br>
        <h1>Normal text <small>small text</small></h1>
        <h5>Normal text <small>small text</small></h5>
        <p>I can highlight text <mark>marked text</mark></p>
        <p>I can highlight text <code>marked text</code></p>
        <p>I can highlight text <kbd>marked text</kbd></p>
        <br>
        <br>
        <br>
        <p class="font-weight-bold">Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
        <p class="font-weight-light">Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
        <p class="font-weight-normal">Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
        <p class="font-italic">Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
        <br>
        <br>
        <br>
        <p class="text-right">Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
        <p class="text-center">Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
        <p class="text-left">Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>    <br>
        <br>
        <br>
        <p class="text-lowercase">Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
        <p class="text-uppercase">Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
        <p class="text-capitalize">Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
    </span>
    </div>
    <div class="display-1 text-center bg-light">Container</div>
    <section class="bg-info">
        <div class="container bg-primary">Simple container</div>
    </section>
    <div class="container-fluid bg-warning">Simple container <mark>fluid</mark></div>
    <br>
    <br>
    <br>
    <div class="display-1 bg-primary text-center">Breakpoints</div>
    <div id="breakpoints" class="container display-3">Breakpoints container</div>
    <style>
        @media screen and (min-width: 576px){
            #breakpoints{
                background: #c30600;
            }
        }

        @media screen and (min-width: 768px){
            #breakpoints{
                background: #c69500;
            }
        }

        @media screen and (min-width: 992px){
            #breakpoints{
                background: #087319;
            }
        }

        @media screen and (min-width: 1200px){
            #breakpoints{
                background: rgba(198, 0, 67, 0.53);
            }
        }

    </style>
    <br>
    <br>
    <br>
    <br>
    <div class="container-fluid">
            <div class="display-1 bg-secondary text-center">ROWs</div>
            <div class="row">
                <div class="col bg-info display-3">Im single col</div>
                <div class="col bg-success display-3">Im single col</div>
            </div>
        <div class="container-fluid">
            <div class="row">
                <div class="col bg-primary display-3">Im single col 1</div>
                <div class="col bg-dark display-3">Im single col 2</div>
                <div class="col bg-warning display-3">Im single col 3</div>
            </div>
        </div>
    </div>
        <br>
        <br>
        <br>
    <div class="container">
        <span class="text-center">
            <div class="h2">Margin</div>
            <p class="bg-danger mr-5">Bootstrap MR5</p>
            <p class="bg-info  mr-4">Bootstrap MR4</p>
            <p class="bg-primary  mr-3">Bootstrap MR3</p>
            <p class="bg-success  mr-2">Bootstrap MR2</p>
            <p class="bg-secondary  mr-1">Bootstrap MR1</p>
            <p class="bg-light mr-0">Bootstrap MR0</p>
        </span>
    </div>

    <div class="container">
        <span class="text-center">
            <div class="h2">Padding</div>
            <p class="bg-danger p-5">Bootstrap P5</p>
            <p class="bg-info  p-4">Bootstrap P4</p>
            <p class="bg-primary  p-3">Bootstrap P3</p>
            <p class="bg-success  p-2">Bootstrap P2</p>
            <p class="bg-secondary  p-1">Bootstrap P1</p>
            <p class="bg-light p-0">Bootstrap P0</p>
        </span>
    </div>

    <div class="container">
        <span class="text-center">
            <div class="h2">Margin t - TOP, b - BOTTOM, l - LEFT, r - RIGHT</div>
            <p class="bg-danger mt-5">Bootstrap MT5</p>
            <p class="bg-info  mb-4">Bootstrap MB4</p>
            <p class="bg-primary  ml-3">Bootstrap P3</p>
            <p class="bg-success  mr-2">Bootstrap P2</p>
            <p class="bg-secondary  my-5">Bootstrap MY-5 top and bottom</p>
            <p class="bg-light mx-4">Bootstrap MX-4 left and right</p>
        </span>
    </div>

    <div class="container">
        <span class="text-center">
            <div class="h2">Padding t - TOP, b - BOTTOM, l - LEFT, r - RIGHT</div>
            <p class="bg-danger pt-5">Bootstrap PT-5</p>
            <p class="bg-info  pb-4">Bootstrap PB-4</p>
            <p class="bg-primary  pl-3">Bootstrap Pl-3</p>
            <p class="bg-success  pr-2">Bootstrap PR-2</p>
            <p class="bg-secondary  py-5">Bootstrap PY-5 top and bottom</p>
            <p class="bg-light px-4">Bootstrap PX-4 left and right</p>
        </span>
    </div>

    <div class="container">
        <span class="text-center">
            <div class="h2">With t - TOP, b - BOTTOM, l - LEFT, r - RIGHT</div>
            <p class="bg-danger w-25 py-1 mx-auto">Bootstrap w-25 + mx-auto = <kbd class="p-0 bg-success">center</kbd></p>
            <p class="bg-info  w-50 mx-auto">Bootstrap w-50</p>
            <p class="bg-primary  w-75 mx-auto">Bootstrap w-75</p>
            <p class="bg-success  w-100 mx-auto">Bootstrap w-100</p>
        </span>
    </div>

</body>
</html>

templates/pages/index.html
{% extends 'base.html' %}
{% load blog_tags %}

{% block title %}Password reset{% endblock %}


{% block content %}
    <p><a href="{% url 'blog:post_list' %}">Blog's posts.</a></p>
    <p><a href="/admin/">Admin.</a></p>
    <p><a href="{% url 'bootstrap' %}">Bootstrap</a></p>
    <p><a href="{% url 'account:edit' %}">Edit profile</a></p>
    <p><a href="{% url 'images:create' %}">Bookmark an image</a></p>
    <p><a href="{% url 'images:images-list' %}">Images list</a></p>
    <p><a href="{% url 'images:ranking' %}">Images ranking</a></p>
{% endblock %}