Django2ByExamples/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

from django.conf import settings
from django.conf.urls.static import static

sitemaps = {'post': PostSitemap}

urlpatterns = [
    path('', include('pages.urls')),
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('account/', include('account.urls', namespace='account')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('images/', include('images.urls', namespace='images')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Функция static() подходит только для локальной разработки, но не для применения на
# боевых серверах. Никогда не используйте Django в качестве поставщика статических
# и медиафайлов.

MyShop/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('', include('shop.urls', namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/urls.py
from django.urls import path, reverse_lazy, re_path
from django.contrib.auth import views as auth_view
from . import views
from .views import MyLogin

app_name = 'account'

urlpatterns = [
    path('users/follow/', views.user_follow, name='user_follow'),
    path('users/', views.user_list, name='user_list'),
    path('user/<username>/', views.user_detail, name='user_detail'),

    # path('login/', views.user_login, name='login'),
    # path('login/', auth_view.LoginView.as_view(), name='login'),
    path('login/', MyLogin.as_view(), name='login'),
    path('logout/', auth_view.LogoutView.as_view(), name='logout'),



    path('password_change/',
         auth_view.PasswordChangeView.as_view(
             success_url=reverse_lazy('account:password_change_done')), name='password_change'),

    path('password_change/done/',
         auth_view.PasswordChangeDoneView.as_view(), name='password_change_done'),


    # -- RESET PASSWORD URLS
    path('password_reset/',
         auth_view.PasswordResetView.as_view(
            success_url=reverse_lazy('account:password_reset_done')), name='password_reset'),

    path('password_reset/done/',
         auth_view.PasswordResetDoneView.as_view(), name='password_reset_done'),

    path('reset/<uidb64>/<token>/',
         auth_view.PasswordResetConfirmView.as_view(
            success_url=reverse_lazy('account:password_reset_complete')), name='password_reset_confirm'),

    path('reset/done/',
         auth_view.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    # -- END OF RESET PASSWORD URLS


    path('register/', views.register, name='register'),
    path('edit/', views.edit, name='edit'),
    path('profile/', views.profile, name='profile'),

    path('', views.dashboard, name='dashboard'),
]

blog/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostsFeed

app_name = 'blog'

urlpatterns = [
    # post views
    path('', views.post_list, name='post_list'),
    # path('', views.PostListView.as_view(), name='post_list'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
    path('search/', views.post_search, name='post_search'),
]

templates/base.html
{% load blog_tags %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static "css/blog.css" %}">
    <!-- Bootstrap -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/bookmarklet.css' %}">
</head>
<body>

<!-- Header -->
{% include  'partials/_header.html' %}
<div class="container-fluid">
<!-- Alerts -->
{% include 'partials/_alerts.html' %}
        <div class="row">
                <div class="col-8 col-md-8">
                    <!-- header -->
                    <div class="container">
                        <div class="row">
                            <div class="col-sm-9">
                                {% block content %}{% endblock %}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-4 col-md-4">
                    <h2><a href="{% url "blog:post_list" %}">My blog</a></h2>
                    <p>This is my blog. Total posts are: {% total_posts %}</p>
                    <p><a href="{% url 'blog:post_feed' %}">Subscribe to my RSS feed</a></p>
                    <h3>Latest posts</h3>
                    {% show_latest_posts 3 %}
                    <h3>Most commented posts</h3>
                    {% get_most_commented_posts 3 as most_commented_post %}
                    <ul>
                        {% for post in most_commented_post %}
                            <li><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></li>
                        {% endfor %}
                    </ul>
                    <p><a href="{% url 'blog:post_search' %}">Search</a></p>
                    <p>
                        {% if request.user.is_authenticated %}
                            <a href="{% url 'account:logout' %}">Logout</a></p>
                        {% else %}
                            <a href="{% url 'account:login' %}">Log-in</a></p>
                        {% endif %}
                </div>
        </div>
</div>
<br>
<br>
<br>
<!-- Footer -->
{% include 'partials/_footer.html' %}

<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'js/lightbox.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script>

<script>
    var csrftoken = Cookies.get('csrftoken');

    function csrfSafeMethod(method){
        // Для этих методов токен не будет подставляться в заголовок.
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }
    $.ajaxSetup({
        beforeSend: function(xhr, settings) {
            if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                xhr.setRequestHeader("X-CSRFToken", csrftoken);
            }
        }
    });

    $(document).ready(function () {
        {% block domready %}{% endblock %}
    });
</script>

</body>
</html>

templates/pagination.html
<div class="pagination">
    <spann class="step-link">
        {% if page.has_previous %}
            <a href="?page={{ page.previous_page_number }}">Previous&nbsp;</a>
        {% endif %}
    </spann>
    <spann class="current">
        Page {{ page.number }} of {{ page.paginator.num_pages }}
    </spann>
    {% if page.has_next %}
        <a href="?page={{ page.next_page_number }}">&nbsp;Next</a>
    {% endif %}
</div>